<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="icon" href="{{ asset('assets/images/website_icon.png') }}">
    <title>Verify Email</title>
    @vite(['resources/js/Panels/Scheduler/Auth/email_verification.js'])
    <link rel="stylesheet" href="{{ asset('css/Panel/Scheduler/Auth/email_verification.css') }}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css">
</head>

<body>

    <header class="header">
        <div class="header-content">
            <div class="logo-section">
                <div class="logo">
                    <img src="{{ asset('assets/images/logo.png') }}" alt="eScheduler Logo">
                </div>
                <span class="admin-label">Scheduler Panel</span>
            </div>
        </div>
    </header>

    <main class="main">
        <div class="login-side">
            <div class="login-content"> 
                <div class="form-header">
                    <h1 class="form-title">Verify Your Email</h1>
                    <p class="form-subtitle">Enter the 6-digit code sent to your email</p>
                    <div class="instructions">
                        <strong>Instructions:</strong> Enter the 6-digit verification code that was sent to your email address. The code will expire in 5 minutes.
                    </div>
                </div>

                <form id="verifyOtpForm">
                    <div class="form-group">
                        <div class="label-container">
                            <label for="otp">Verification Code</label>
                            <span class="timer" id="timer">05:00</span>
                        </div>
                        <div class="otp-container" id="otpContainer">
                            <!-- OTP inputs will be generated by JavaScript -->
                        </div>
                        <div class="error-message" id="otpError"></div>
                    </div>

                    <div class="buttons-container">
                        <button type="submit" class="submit-btn" id="submitBtn">
                            <i class="fas fa-check-circle"></i>
                            <span id="btnText">Verify OTP</span>
                        </button>
                    </div>

                    <div class="resend-row">
                        <span class="resend-text">Didn't receive a code?</span>
                        <a href="#" class="resend-link disabled" id="resendLink">Resend</a>
                    </div>
                </form>
            </div>
        </div>
    </main>

    <footer class="simple-footer">
        <div class="footer-content">
            <div class="copyright">
                &copy; 2026 eScheduler. Scheduler Panel.
            </div>
        </div>
    </footer>

</body>
</html>